// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// testMalloc
void testMalloc();
RcppExport SEXP _curand_testMalloc() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    testMalloc();
    return R_NilValue;
END_RCPP
}
// rand_num
void rand_num();
RcppExport SEXP _curand_rand_num() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    rand_num();
    return R_NilValue;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _curand_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_curand_testMalloc", (DL_FUNC) &_curand_testMalloc, 0},
    {"_curand_rand_num", (DL_FUNC) &_curand_rand_num, 0},
    {"_curand_rcpp_hello_world", (DL_FUNC) &_curand_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_curand(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
