# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' CUDA test malloc
#' @export
testMalloc <- function() {
    invisible(.Call(`_curand_testMalloc`))
}

#' Calculates random numbers
#' @export
rand_num <- function() {
    invisible(.Call(`_curand_rand_num`))
}

#' CUDA hello world
#' @export
rcpp_hello_world <- function() {
    .Call(`_curand_rcpp_hello_world`)
}

